server:
  port: 8000
logging:
  level:
    com.gqz.crm: debug
spring:
  application:
    name: boot_crm
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/boot_crm
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jackson:
    locale: zh
    time-zone: GMT+8
    date-format: yyyy-MM-dd hh:mm:ss
  thymeleaf:
    cache: false
    encoding: UTF-8
  transaction:
    default-timeout: 3000
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.gqz.crm.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



